### ISSUE TITLE
Trying to use similar method, failing?

### ISSUE THREAD

**Issue by bitsofinfo** [typesafehub/activator-akka-java-spring#12]
I am trying to use this method of a Spring "extension". In my Spring java config class I have a bean defined like

```
... public class TestActor extends UntypedActor {...

@Bean
public TestActor testActor() {
    return new TestActor();
}
```

Then I have a spring unit-test that loads off this Java config and does...

```
ActorRef testActor = myAkkaSystemBean.actorOf(SpringExtProvider.get(system).props("TestActor"),"TestActor");
```

Then I get this exception:

```
Caused by: akka.actor.ActorInitializationException: You cannot create an instance of [org.bitsofinfo.coredata.experimental.akka.TestActor] explicitly using the constructor (new). You have to use one of the 'actorOf' factory methods to create a new actor. See the documentation.
    at akka.actor.ActorInitializationException$.apply(Actor.scala:173)
    at akka.actor.Actor$class.$init$(Actor.scala:436)
    at akka.actor.UntypedActor.<init>(UntypedActor.scala:97)
    at org.bitsofinfo.coredata.experimental.akka.TestActor.<init>(TestActor.java:11)
    at org.bitsofinfo.coredata.experimental.akka.AkkaConfig.testActor(AkkaConfig.java:33)
    at org.bitsofinfo.coredata.experimental.akka.AkkaConfig$$EnhancerBySpringCGLIB$$204aa21.CGLIB$testActor$0(<generated>)
    at org.bitsofinfo.coredata.experimental.akka.AkkaConfig$$EnhancerBySpringCGLIB$$204aa21$$FastClassBySpringCGLIB$$f4f62948.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
    at org.bitsofinfo.coredata.experimental.akka.AkkaConfig$$EnhancerBySpringCGLIB$$204aa21.testActor(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    ... 44 common frames omitted
```

So my question is, how can I define all my actors in spring XML or java config, then just load them by name if constructing them, blows up like this?

**Comment by bitsofinfo** [comment]
adding `@Scope("prototype")` fixes it but its still not entirely clear what detected that and determined not to throw that error, the method is still doing "new..."

**Comment by bantonsson** [comment]
Hi @bitsofinfo

If you look at the code in the sample e.g. the `CountingActor`, you will see a note in the code comment that reads: **The scope here is prototype since we want to create a new actor instance for use of this bean.**

It seems like the `@Bean` annotation creates a singleton instance by default, which will be created outside of the `actorOf` call, and that is what the error message is trying to tell you.

I guess things are working now, that you have the scope set to prototype?

**Comment by bitsofinfo** [comment]
yep works w/ prototype. was just curious as to what is able to detect a class being instantiated the way I had it vs. a prototype scoped one... must check the annotation or something. Either way a new instance is being constructed, just didn't know how it was detecting the diff
